<!-- formulaire pour l'ajout d'un scenario' -->
<div class="container bg-dark text-white p-2" style="display:none" id="mdAddScenario">
    <div class="row">
        <div class="col-12">
            <label for="inputSctitre" class="form-label">Titre</label>
            <input type="text" class="form-control" id="inputSctitre" />
        </div>
        <div class="col-12">
            <label for="inputScdesc" class="form-label">Description</label>
            <textarea id="inputScdesc" class="form-control" rows="2"></textarea>
        </div>
    </div>
    <div class="d-flex justify-content-between mt-2">
        <button id='btnSccreate' class="btn btn-danger" >Create</button>
    </div>
</div>
