<!-- formulaire pour visualiser la sélection des médias' -->
<div class="container bg-dark text-white p-2" style="display:none" id="mdSelection">


<div class="player-container">
    <video
      id="playerSelection"
      class="video-js"
      height="300"
      width="600"
      controls>
    </video>

    <div class="vjs-playlist">
      <!--
        The contents of this element will be filled based on the
        currently loaded playlist
      -->
    </div>
</div>
