<?php
if($page->slug()=='ajax'){
    echo $this->partial('edisem/'.$page->slug(), []);
    return;
}


$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo 
    $this->content; 
    if($page->slug()=='visios'){
        echo $this->partial('edisem/visios');
    }
    if($page->slug()=='scenarios'){
        echo $this->partial('edisem/scenarios');
    }
    if($page->slug()=='jdc'){
        echo $this->partial('edisem/jdc');        
    }
    if($page->slug()=='sparnatural'){
        echo $this->partial('edisem/sparnatural');        
    }    
    ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
