<?php
$isAdmin = $this->vars('isAdmin');
$allowCreate = $this->vars('allowCreate');

?>
<ul class="nav nav-pills" id="tabVisioDroite" >
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="listeSeminaire-tab" data-bs-toggle="tab" data-bs-target="#listeSeminaire" type="button" role="tab" aria-controls="listeSeminaire" aria-selected="true">Séminaires</button>
  </li>
  <?php if($allowCreate) : ?>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="indexVisio-tab" data-bs-toggle="tab" data-bs-target="#indexVisio" type="button" role="tab" aria-controls="indexVisio" aria-selected="false">Annoter</button>
  </li>
  <?php endif; ?>
</ul>
<div class="tab-content" id="tabVisioDroiteContent">
  <div class="tab-pane fade show active" id="listeSeminaire" role="tabpanel" aria-labelledby="listeSeminaire-tab">
      <div class="list-group" id="listeSem">
      </div>     
  </div>
  <?php if($allowCreate) : ?>
  <div class="tab-pane fade" id="indexVisio" role="tabpanel" aria-labelledby="indexVisio-tab">
      <?php echo $this->partial('edicem/form-indexer-manu', ['isAdmin'=>$isAdmin,'allowCreate'=>$allowCreate]);?>      
  </div>
  <?php endif; ?>

</div>