<?php
$allowAnnotation=false;
if ($this->userIsAllowed(\Annotate\Entity\Annotation::class, 'create')) {
  $allowAnnotation=true;
}
$allowCreate=false;
if ($this->userIsAllowed('Omeka\Entity\Resource', 'create')) {
  $allowCreate=true;
}
$isAdmin = $this->identity() && $this->identity()->getRole() == "global_admin" ? true : false;
$translate = $this->plugin('translate');

//récupère la liste des scénarios
$scenarios = $this->api()->search('items', ['resource_class_id'=>1085,'sort_by'=>'dcterms:date'])->getContent();

$actant = false;
if($allowCreate)$actant=$this->CartoAffectFactory(['getActant'=>true,'user'=>$this->identity()]); 


?>
<script>

const itemsScenario = <?php echo json_encode($scenarios); ?>    

    , actant = <?php echo json_encode($actant); ?>    

    , urlApi = '<?php echo $this->url('api', [], true); ?>'
    , urlAdmin = '<?php echo $this->url('admin', [], true); ?>'
    , urlSite = '<?php echo $this->url('site', [], true); ?>'
    , urlPosterVideo="<?php echo $this->assetUrl('images/video-poster.png'); ?>"
;

window.onload = initVisios;
</script>

<div class="container-fluid h-75">
  <div class="row">
    <div class="col bg-secondary text-white p-2">
      <?php echo $this->partial('edicem/tb-scenarios', ['isAdmin'=>$isAdmin,'allowCreate'=>$allowCreate]);?>
      <?php echo $this->partial('edicem/form-edit-index', ['isAdmin'=>$isAdmin,'allowCreate'=>$allowCreate]);?>
      <?php echo $this->partial('edicem/form-ajout-layer');?>
      <div class="container">
        <div id="mediaCards" class="card-group"></div>
      </div>
    </div>
  </div>
</div>

<script type="module">

import { Timeliner } from '<?php echo $this->assetUrl('js/timeliner/timeliner.js'); ?>'

var actions = {};

// initialize timeliner
timeliner = new Timeliner(actions);
timeliner.hide();
timeliner.fctKeyframe = addKeyframe;
timeliner.fctKeyframeMove = changeKeyframe;
timeliner.fctAddLayer = addLayer;
</script>
